"use client";

/**
 * InterviewReport — Beautiful post-interview evaluation report card.
 */
export default function InterviewReport({ payload }) {
  if (!payload) return null;

  const getRatingColor = (rating) => {
    const r = (rating || "").toLowerCase();
    if (r.includes("strong hire")) return "rating-strong-hire";
    if (r.includes("hire")) return "rating-hire";
    if (r.includes("lean no")) return "rating-lean-no";
    if (r.includes("no hire")) return "rating-no-hire";
    return "rating-default";
  };

  return (
    <div className="report-container">
      {/* Report Header */}
      <div className="report-header">
        <div className="report-header-glow" />
        <div className="report-icon">📋</div>
        <h2 className="report-title">Interview Evaluation Report</h2>
        <p className="report-subtitle">
          AI-Generated Technical Assessment Summary
        </p>
      </div>

      {/* Final Rating */}
      <div className={`report-rating ${getRatingColor(payload.final_rating)}`}>
        <span className="rating-label">Final Rating</span>
        <span className="rating-value">{payload.final_rating}</span>
      </div>

      {/* Summary */}
      {payload.summary && (
        <div className="report-section report-summary">
          <h3 className="report-section-title">
            <span className="section-icon">💬</span>
            Summary
          </h3>
          <p className="summary-text">{payload.summary}</p>
        </div>
      )}

      {/* Topic Scores */}
      {payload.topic_scores &&
        Object.keys(payload.topic_scores).length > 0 && (
          <div className="report-section">
            <h3 className="report-section-title">
              <span className="section-icon">📊</span>
              Topic Scores
            </h3>
            <div className="scores-grid">
              {Object.entries(payload.topic_scores).map(
                ([topic, score], i) => (
                  <div key={i} className="score-item">
                    <div className="score-topic">{topic}</div>
                    <div className="score-bar-track">
                      <div
                        className="score-bar-fill"
                        style={{ width: `${(score / 10) * 100}%` }}
                      />
                    </div>
                    <span className="score-value">{score}/10</span>
                  </div>
                )
              )}
            </div>
          </div>
        )}

      {/* Strengths */}
      {payload.strengths?.length > 0 && (
        <div className="report-section">
          <h3 className="report-section-title">
            <span className="section-icon">✅</span>
            Strengths
          </h3>
          <ul className="report-list strengths-list">
            {payload.strengths.map((s, i) => (
              <li key={i} className="report-list-item strength-item">
                <span className="list-bullet strength-bullet">●</span>
                {s}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Areas for Improvement */}
      {payload.areas_for_improvement?.length > 0 && (
        <div className="report-section">
          <h3 className="report-section-title">
            <span className="section-icon">🔧</span>
            Areas for Improvement
          </h3>
          <ul className="report-list improvements-list">
            {payload.areas_for_improvement.map((a, i) => (
              <li key={i} className="report-list-item improvement-item">
                <span className="list-bullet improvement-bullet">●</span>
                {a}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Footer */}
      <div className="report-footer">
        <p className="footer-text">
          Generated by AB Talks AI Interview Agent
        </p>
        <p className="footer-timestamp">
          {new Date().toLocaleString("en-US", {
            dateStyle: "full",
            timeStyle: "short",
          })}
        </p>
      </div>
    </div>
  );
}
